<?php
/**
 * Copyright (c) 2018 OBiBa. All rights reserved.
 *
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
* @file
* Mica List Facet files
*/

define('SEARCH_FILTER', 'mica/search-filter');


/**
 * Implements hook_theme().
 *
 */
function obiba_mica_search_filter_theme($existing, $type, $theme, $path) {
  $path_views_theme = $path . '/js/app/views';
  return array(
    'search-result-search-filter-template' => array( // the main search template app  that is overridable
                                                     // see <module>/js/app/views/search-result-list-template.tpl.php
                                                     // where we have add a custom directive filterSearchInputWidget
      'template' => 'search-result-list-template',
      'path' => $path_views_theme,
    ),
    'filter-name-search-widget' => array(
      'template' => 'filter-name-search-widget',
      'path' => $path_views_theme,
    ),
  );

}
/* <!-- Here Obiba Mica Hooks API to enable obiba angular custom app --> */
/**
 * Implements hook_load_menus().
 */
function obiba_mica_search_filter_load_menus() {
  return array(
    SEARCH_FILTER => array(
      'access callback' => TRUE,
      'title' => 'Search Filter',
      'module_caller' => 'obiba_mica_search_filter',
      'menu_name' => 'main-menu',
      'type' => MENU_NORMAL_ITEM,
      'expanded' => TRUE,
      'weight' => 2,
      'options' => array('fragment' => 'search'),
    )
  );
}

/**
 * Implements hook_get_ng_module_to_load().
 */
function obiba_mica_search_filter_get_ng_module_to_load() {
  if (in_array(current_path(), array(SEARCH_FILTER))) {
    obiba_mica_search_filter_options();
    return 'mica.obibaSearchFilter';
  }
  return FALSE;
}

/**
 * Implements hook_get_js().
 */
function obiba_mica_search_filter_get_js($weight_js) {
  if (in_array(current_path(), array(SEARCH_FILTER))) {
    $module_path = drupal_get_path('module', 'obiba_mica_search_filter');
    $js = file_scan_directory($module_path . '/js/app', '/.*\.js$/', array('key' => 'name'));
    ksort($js);
    foreach ($js as $file_js) {
      drupal_add_js($file_js->uri, array(
        'type' => 'file',
        'scope' => 'footer',
        'weight' => ++$weight_js,
      ));
    }
  }
  return ++$weight_js;
}

/* <!--  end of obiba mica hooks --> */

/*
 * Custom Search options used to override the default obiba angular search app behavior
 */
function obiba_mica_search_filter_options(){
  $list_override_themes = obiba_mica_commons_enabled_theme(array(
    'searchResultList' => 'search-result-search-filter-template', // template to override
  ));

  drupal_add_js(array(
    'obibaListOptions' => array(
      'listSearchOptions' => array(
        'variable' => array( // variable fields in the result
          'fields' => array(
            "attributes.label.*",
            "variableType",
            "datasetId",
            "datasetAcronym"
          ),
        ),
      ),
    ),
    'obibaSearchFilterearchOptions' => array(
      'resultTabsOrder' => array('variable'), //Display only variable result table
      'targetTabsOrder' => array('variable'), //Display only variable target tab
      'searchTabsOrder' => array('list'), // Display only the list tab
    ),
    'listOverrideThemes' => !empty($list_override_themes) ? $list_override_themes : NULL,
  ),
    'setting');
}
